# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: andap

development:
  <<: *default
  database: myapp_db

test:
  <<: *default
  database: myapp_db

production:
  <<: *default
  database: myapp_db
